sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t sychang0422/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true sychang0422/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: '${region name}'
  app: 'docker-react-app'
  env: 'DockerReactApp-env'
  bucket_name: '${bucket name}'
  bucket_path: 'docker-react-app'
  on:
    branch: master # master에 푸시 시 실행
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
